export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS';
export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS';
export const CHANGE_VALUE = 'CHANGE_VALUE';
export const CREATE_TRACK_SUCCESS = 'CREATE_TRACK_SUCCESS';
export const DELETE_TRACK_SUCCESS = 'DELETE_TRACK_SUCCESS';